<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <GalaxyPackages>$(MSBuildThisFileDirectory)..\.tools\driver-packages\</GalaxyPackages>
  </PropertyGroup>
  <Import Project="$(GalaxyPackages)Microsoft.Windows.WDK.x64.10.0.28000.2526\build\native\Microsoft.Windows.WDK.x64.props" Condition="Exists('$(GalaxyPackages)Microsoft.Windows.WDK.x64.10.0.28000.2526\build\native\Microsoft.Windows.WDK.x64.props')" />
  <Import Project="$(GalaxyPackages)Microsoft.Windows.SDK.CPP.x64.10.0.28000.1721\build\native\Microsoft.Windows.SDK.cpp.x64.props" Condition="Exists('$(GalaxyPackages)Microsoft.Windows.SDK.CPP.x64.10.0.28000.1721\build\native\Microsoft.Windows.SDK.cpp.x64.props')" />
  <Import Project="$(GalaxyPackages)Microsoft.Windows.SDK.CPP.10.0.28000.1721\build\native\Microsoft.Windows.SDK.cpp.props" Condition="Exists('$(GalaxyPackages)Microsoft.Windows.SDK.CPP.10.0.28000.1721\build\native\Microsoft.Windows.SDK.cpp.props')" />
</Project>
